import type { DestinationAttributes } from "@/domain/destination";

/**
 * The single source of truth for the seeded destinations. A destination is
 * identified by its name + country, so editing a row here and re-seeding updates
 * it in place.
 */
export const catalogue: readonly DestinationAttributes[] = [
  {
    name: "Machu Picchu",
    country: "Peru",
    region: "South America",
    costLevel: "Moderate",
    activities: ["Hiking & Trekking", "Cultural Tours", "Photography", "Historical Sightseeing"],
    averageDailyBudget: 150,
    annualVisitors: 1_500_000,
  },
  {
    name: "Santorini",
    country: "Greece",
    region: "Europe",
    costLevel: "Premium",
    activities: ["Beach & Relaxation", "Food & Wine Tasting", "Photography", "Sailing & Boating"],
    averageDailyBudget: 250,
    annualVisitors: 2_000_000,
  },
  {
    name: "Kyoto",
    country: "Japan",
    region: "Asia",
    costLevel: "Moderate",
    activities: ["Cultural Tours", "Historical Sightseeing", "Food & Wine Tasting", "Photography"],
    averageDailyBudget: 180,
    annualVisitors: 5_300_000,
  },
  {
    name: "Serengeti National Park",
    country: "Tanzania",
    region: "Africa",
    costLevel: "Premium",
    activities: ["Wildlife Safari", "Photography", "Hot Air Ballooning", "Camping"],
    averageDailyBudget: 300,
    annualVisitors: 350_000,
  },
  {
    name: "Queenstown",
    country: "New Zealand",
    region: "Oceania",
    costLevel: "Premium",
    activities: ["Adventure Sports", "Skiing & Snowboarding", "Hiking & Trekking", "Paragliding"],
    averageDailyBudget: 200,
    annualVisitors: 3_000_000,
  },
  {
    name: "Reykjavik",
    country: "Iceland",
    region: "Europe",
    costLevel: "Premium",
    activities: ["Hiking & Trekking", "Hot Air Ballooning", "Photography", "Volcano Tours"],
    averageDailyBudget: 280,
    annualVisitors: 2_300_000,
  },
  {
    name: "Cusco",
    country: "Peru",
    region: "South America",
    costLevel: "Budget",
    activities: [
      "Hiking & Trekking",
      "Cultural Tours",
      "Historical Sightseeing",
      "Food & Wine Tasting",
    ],
    averageDailyBudget: 60,
    annualVisitors: 2_700_000,
  },
  {
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    costLevel: "Budget",
    activities: ["Beach & Relaxation", "Surfing", "Yoga & Wellness Retreats", "Cultural Tours"],
    averageDailyBudget: 70,
    annualVisitors: 6_200_000,
  },
  {
    name: "Banff National Park",
    country: "Canada",
    region: "North America",
    costLevel: "Moderate",
    activities: [
      "Hiking & Trekking",
      "Skiing & Snowboarding",
      "Kayaking & Canoeing",
      "Wildlife Safari",
    ],
    averageDailyBudget: 180,
    annualVisitors: 4_000_000,
  },
  {
    name: "Patagonia",
    country: "Argentina",
    region: "South America",
    costLevel: "Premium",
    activities: ["Hiking & Trekking", "Rock Climbing", "Photography", "Camping"],
    averageDailyBudget: 220,
    annualVisitors: 400_000,
  },
  {
    name: "Marrakech",
    country: "Morocco",
    region: "Africa",
    costLevel: "Budget",
    activities: [
      "Cultural Tours",
      "Food & Wine Tasting",
      "Historical Sightseeing",
      "Nightlife & Entertainment",
    ],
    averageDailyBudget: 55,
    annualVisitors: 3_000_000,
  },
  {
    name: "Dubrovnik",
    country: "Croatia",
    region: "Europe",
    costLevel: "Moderate",
    activities: [
      "Historical Sightseeing",
      "Beach & Relaxation",
      "Kayaking & Canoeing",
      "Food & Wine Tasting",
    ],
    averageDailyBudget: 160,
    annualVisitors: 1_400_000,
  },
  {
    name: "Cancun",
    country: "Mexico",
    region: "North America",
    costLevel: "Moderate",
    activities: [
      "Beach & Relaxation",
      "Scuba Diving & Snorkeling",
      "Nightlife & Entertainment",
      "Cultural Tours",
    ],
    averageDailyBudget: 140,
    annualVisitors: 8_000_000,
  },
  {
    name: "Phuket",
    country: "Thailand",
    region: "Asia",
    costLevel: "Budget",
    activities: [
      "Beach & Relaxation",
      "Scuba Diving & Snorkeling",
      "Food & Wine Tasting",
      "Nightlife & Entertainment",
    ],
    averageDailyBudget: 80,
    annualVisitors: 9_500_000,
  },
  {
    name: "Swiss Alps",
    country: "Switzerland",
    region: "Europe",
    costLevel: "Luxury",
    activities: ["Skiing & Snowboarding", "Hiking & Trekking", "Rock Climbing", "Photography"],
    averageDailyBudget: 400,
    annualVisitors: 1_200_000,
  },
];
